name: Rails Tests

on:
  push:
    # No branch specified - runs on all branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.3'
        bundler-cache: true
    
    - name: Install SQLite3
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev
    
    - name: Install dependencies
      run: bundle install
    
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Set up Database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load
    
    - name: Run tests
      run: bundle exec rails test:all
